# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=8192)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('fk_article', models.ManyToManyField(to='fgs_blog.Articles')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fgs_blog.Authors'),
        ),
    ]
