# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgs_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='header',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
