# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgs_blog', '0002_auto_20160927_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=8192, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
