# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgs_blog', '0003_articles_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='fk_article',
        ),
        migrations.AddField(
            model_name='articles',
            name='fk_article',
            field=models.ManyToManyField(to='fgs_blog.Tags'),
        ),
    ]
